### ISSUE TITLE
问

### ISSUE THREAD

**Issue by G-Cao** [0809zheng/0809zheng.github.io#10]
你好，可以请问一下，在长尾采样策略中，Class-balanced sampling根据公式不是每个样本采样概率是1/C，但是代码给的是1/n_C，每个类别样本数的倒数，请问这两种到底是怎么计算的，谢谢了

**Comment by 0809zheng** [comment]
应该是按1/n_C（每个类别样本数的倒数）；公式里C想表达类别的势，等价于n_C。
