### ISSUE TITLE
请教一下RF-Based 3D Skeletons为什么使用FMCW而不是使用WiFi的CSI呢？

### ISSUE THREAD

**Issue by ziyuhuang123** [0809zheng/0809zheng.github.io#13]
嗨！请问为什么不用CSI呢？我知道CSI的精度不如FMCW，不过WiFi也更为常见，不使用的原因是不能，还是只是没有尝试过呢？多谢！

**Comment by 0809zheng** [comment]
这个团队(MIT CSAIL)的RF-based系列工作一直使用FMCW体系，应该是一脉相承吧
