### ISSUE TITLE
请教一下关于SOM自组织映射神经网络的知识

### ISSUE THREAD

**Issue by SwaggyZhang** [0809zheng/0809zheng.github.io#14]
您好，近日读到了您关于SOM的文章，有一些地方理解的不是很好，向您请教。

1. U-matrix可视化里的节点数表示的是什么呢？
2. SOM的输出是否就是它本身，也就是一个调整参数后的网络？
3. 关于各个变量的component planes是怎么从SOM得到的呢？

期待您的回答

**Comment by 0809zheng** [comment]
1. 节点数就是SOM模型定义的节点数（二维形式为X×Y）；
2. SOM的输出就是它的节点权重；
3. component plane是指什么，能否详细描述一下？

**Comment by SwaggyZhang** [comment]
感谢您的解答！

component plane是我看到一些英文文献里的术语，他们将绘制的每个变量的热力图称为component plane。

不知道我这样的解释是否清楚？

**Comment by 0809zheng** [comment]
查阅了一下相关资料，SOM的输出是节点权重($W \in \mathbb{R}^{X \times Y \times n}$)，component plane是指可视化输出权重的$n$个特征维度（即生成$n$个$X\times Y$的热力图），从而分析每个权重节点对哪些特征维度更敏感。

**Comment by SwaggyZhang** [comment]
感谢您的回答~
