### ISSUE TITLE
Transformer计算复杂度讨论

### ISSUE THREAD

**Issue by ShunLu91** [0809zheng/0809zheng.github.io#17]
尊敬的作者，
您好！

在这篇[博客](https://0809zheng.github.io/2021/07/12/efficienttransformer.html?)中，1.2小节归一化注意力矩阵A的计算复杂度似乎有问题：对于N*N的矩阵使用softmax逐行归一化时，每一行的每个元素都需要算exp，因此每一行的计算复杂度应该为O(N)，因为一共有N行，所以归一化计算的计算复杂度应该为O(N²)。

感谢您的分享，受益匪浅。祝好！

陆顺

**Comment by 0809zheng** [comment]
您好，
感谢您的指正！

在[1.2小节](https://0809zheng.github.io/2021/07/12/efficienttransformer.html?#2-%E8%87%AA%E6%B3%A8%E6%84%8F%E5%8A%9B%E6%9C%BA%E5%88%B6%E7%9A%84%E8%BF%90%E7%AE%97)中，针对自注意力机制计算复杂度的讨论主要是围绕**矩阵乘法**进行的，忽略了加法、指数等运算。尽管**Softmax**也会引入$O(N^2)$复杂度，但该操作本身通常难以优化，因此未在原文展开讨论。相关说明会在近期的更新中修正。

再次感谢您的建议: )
